# Schema for SACDA theme settings.

sacda.settings:
  type: theme_settings
  label: 'SACDA theme settings'
  mapping:
    footer_partners:
      type: sequence
      label: 'Footer partners'
      sequence:
        type: mapping
        label: 'Partner'
        mapping:
          name:
            type: string
            label: 'Partner name'
          image_fid:
            type: integer
            label: 'Partner image file ID'
          link:
            type: string
            label: 'Partner link URL'
          weight:
            type: integer
            label: 'Weight'
    footer_social_links:
      type: sequence
      label: 'Footer social links'
      sequence:
        type: mapping
        label: 'Social link'
        mapping:
          title:
            type: string
            label: 'Title'
          icon:
            type: string
            label: 'Icon name'
          link:
            type: string
            label: 'URL'
          weight:
            type: integer
            label: 'Weight'
    carousel_autoplay_speed:
      type: integer
      label: 'Carousel autoplay speed (ms)'
    carousel_slides:
      type: sequence
      label: 'Carousel slides'
      sequence:
        type: mapping
        label: 'Slide'
        mapping:
          image_fid:
            type: integer
            label: 'Image file ID'
          title:
            type: string
            label: 'Title'
          subtitle:
            type: string
            label: 'Subtitle'
          link:
            type: string
            label: 'Link URL'
